### PR TITLE
Add documentation and examples

### LINKED ISSUE #17: Documentation on how to use?
There are some tantalizing hints in issue #16, as well as the Pastebin at https://pastebin.com/0pchfKcG, but still unwritten (as far as I can tell) is:

* Where does the config file from the Pastebin go?
* Is the config in the Pastebin complete?
* How is Cartographer triggered once it is configured?

I'm happy to write up a HOWTO and PR it, but first I need to know "how to". :sim

### PR DESCRIPTION
**Pull request by krisalyssa**
Fixes #17 (or at least starts the documentation which will fix it 😃 ).

### CODE REVIEW

**Comment by CraigCottingham** [comment]
@Sigma88 Am I correct in reading that there's currently no difference between the satellite version of a map (e.g. `satelliteBiome`) and the non-satellite version (e.g. `biomeMap`)?

**Comment by Sigma88** [comment]
No there is a difference (there should be unless some errors occur)

biomeMap is a simple biome map

satelliteBiome is a biome map with overlayed a normal map to give an impression of 3D structure (same as colorMap vs satelliteMap)

**Comment by krisalyssa** [comment]
@Sigma88 As far as I can tell, there _is_ no wiki. When I click on the link at the top of the page (https://github.com/Sigma88/Sigma-Cartographer/wiki), I'm just redirected back to the main repo page.

**Comment by Sigma88** [comment]
hey, I don't know why that happens.
I created the first page of the wiki now, maybe that is enough to allow you access

**Comment by krisalyssa** [comment]
I can see it now, but I don't have permission to edit it. I think I need to have write permission in the repository for that. Would you rather just wait for an updated PR?

**Comment by Sigma88** [comment]
Hmm that's weird, wikis are supposed to be editable by anyone. Like wikipedia.
I'll take a look if there are any settings I need to check for that.

I would rather use the wiki for those things, I think it looks nicer.

**Comment by Sigma88** [comment]
Ok, there was a setting active that limited the wiki to only members of the project.
Now it \*should\* be open to be edited by anyone

**Comment by krisalyssa** [comment]
I just refreshed the wiki and now I have an "Edit" button. I'll start moving documentation into it.

**Comment by Sigma88** [comment]
Thanks a lot!

**Pull request closed without merging**
